### ISSUE TITLE
better-jumper-forward/backward not working with `lsp-find-references`

### ISSUE THREAD

**Issue by SreenivasVRao** [gilbertw1/better-jumper#13]
Hi - many thanks for this package! :) I use it a lot with doom-emacs.

It was working fine for a while, and it stopped working over the past couple of months. I usually use `lsp-find-definition` to get to the definition and `better-jumper-backward` to jump backward. definitions are in the same or different buffers. `better-jumper-forward` would take me back to the definition.

Now I'm seeing it fail to work - I can't really tell why. There's no response for `jump-forward`/`jump-backward`

Doom Emacs with gccemacs on OSX if it helps.

**Comment by gilbertw1** [comment]
Hi,

Sorry for taking so long to respond. Better jumper doesn't actually capture jumps, moreso it exposes functions to add, track, and navigate between jumps. It's possible that `doom-emacs` has changed or removed some hooks around this functionality, however you can create a function that adds a jump then performs the definition lookup like this:

```lisp
(defun jump-to-def ()
    (interactive)
    (better-jumper-set-jump)
    (lsp-find-definition))
```

The above function should work the way you expect.

**Comment by SreenivasVRao** [comment]
Thanks - that seems to have done the trick! :)
