### ISSUE TITLE
Use better-jump--last-jump-pos to detect duplicate calls of better-jumper-set-jump cause unexpected behavior (when use evil-mode)

### ISSUE THREAD

**Issue by CloseToZero** [gilbertw1/better-jumper#15]
`better-jump--last-jump-pos` is added at 7ae4011 to resolve #5, but it causes unexpected behavior  (when use evil-mode).

**Steps to reproduce:**

Insert text:
```
abc-123
abc-456
abc-789
```

Search `abc` **three times** starting from the top of text by press `/` once and press `n` twice in normal state (NOTE: I use `evil-search` search module). After searching, the cursor position should at the third `abc`. Press `C-o` to go back to the second `abc` and then press `/` to search `456`. Finally, press `C-o` again, I expect the cursor should go back to the second `abc`, but it goes to the first `abc`.

The reason is that `better-jump--last-jump-pos` is the same as `(point)` when I search `456` thus ignored by the advice of `evil-set-jump`.

Maybe we should use `evil--jumps-jumping-backward` to resolve #5 instead?
The following workaround seems work fine:

```emacs-lisp
(with-eval-after-load 'better-jumper
  (define-advice better-jumper--jump (:after (&rest _))
    "Don't use `better-jump--last-jump-pos' to detect duplicate calls of `better-jumper-set-jump'."
    (setq better-jump--last-jump-pos nil))
  
  ;; Instead, set `evil--jumps-jumping-backward' to non-nil to let
  ;; evil-mode know that we just jumped backward. It will be cleared
  ;; by evil-mode automatically.
  (add-hook 'better-jumper-post-jump-hook
            (lambda () (setq evil--jumps-jumping-backward t))))
```

**Comment by gilbertw1** [comment]
Hey, thanks for taking the time to report this issue and research a workaround. I'll look into this shortly and test your suggestion.

**Comment by CloseToZero** [comment]
By the way, the current implementation of evil-jumps won't push a jump point when opening a file by `find-file`, `find-file` won't satisfy the condition of `evil--jump-handle-buffer-crossing` to push a jump point.

For `find-file` to work with `C-o`, I have to add the following code (**with or without my workaround in previous comment**):

```emacs-lisp
(evil-set-command-property 'find-file :jump t)
```

For doom-emacs users:

```emacs-lisp
(advice-add #'find-file :around #'doom-set-jump-a)
```

**Comment by gilbertw1** [comment]
Thanks for pointer, I believe your suggestion was definitely the correct approach here. I've pushed an update incorporating those changes. 

Regarding your followup comment, I'm a bit torn. I think that having evil set a jump when `find-file` is invoked is definitely desirable. However, I'm not sure that `better-jumper` should be altering the behavior of `evil` whenever it's enabled versus leaving stock behavior alone and letting a user configure it themselves. I'll have to think on that one a bit more.

**Comment by CloseToZero** [comment]
Thanks for your quick reply and this amazing package :+1: , now everything is work as expected, I finally can press `C-o` without fear :blush:.

**Comment by CloseToZero** [comment]
I just have found a strange phenomenon :joy:, the reason that `find-file` won't be considered as cross buffers is that `post-command-hook` runs before the value of  `window-buffer` changed...

I have tried to trace why this happens, but it seems not an easy task, and I have work to do. I would like to stick to set a jump manually right now, at least it works fine :joy:.
