### ISSUE TITLE
better-jumper-jump-forward dont jump buffers like better-jumper-jump-backward 

### ISSUE THREAD

**Issue by otavioschwanck** [gilbertw1/better-jumper#5]
What did you expect to happen?
better-jumper-jump-forward (C-i) jump buffers (files)

What actually happened?
better-jumper-jump-forward (C-i) don't jump buffers like the backward version (C-o)

Steps to reproduce:

1. Open one file
2 Open another fifle
3. Press C-o to go back to first file
4. Press C-i (should go back to second file)

Issue from doom emacs:
https://github.com/hlissner/doom-emacs/issues/4050

**Comment by gilbertw1** [comment]
Looking into it. It looks like evil was recently updated in a way that interferes with better jumper when crossing buffer boundaries:

 emacs-evil/evil@cc6324bfd214211fe0259290b322dccfbdcf447f

**Comment by gilbertw1** [comment]
Alright this issue has been resolved.
